name: 'Copy spectral rule file'
description: ''

inputs:
  working-directory:
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    # Copy files
    - name: Copy spectral rule file
      shell: bash
      run: |
        cp  ${{ github.action_path }}/files/spectral.yaml ${{ inputs.working-directory }}/.spectral.yaml
