codecov:
  require_ci_to_pass: true
  branch: main
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    patch: false
    project:
      default: false
      backend:
        target: 80%
        flags:
          - notifyapi
          - notifydelivery

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:                  # this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: false       # [true :: must have a head report to post]

flags:
  notifyapi:
    paths:
      - notify-api/src/notify_api
    carryforward: true
  notifydelivery:
    paths:
      - notify-delivery/src/notify_delivery
    carryforward: true