name: "Frontend application deployment files"
description: ""

inputs:
  working-directory:
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    # Copy files
    - name: Copy build/deployment files
      shell: bash
      run: |
        ls -l ${{ github.action_path }}/files
        cp  ${{ github.action_path }}/files/* ${{ inputs.working-directory }}
        ls -l ${{ inputs.working-directory }}
