version: 1
disable_existing_loggers: True

formatters:
  mainFormatter:
    format: '{"timestamp": "%(asctime)s", "severity": "%(levelname)s", "message": "%(message)s", "additional": %(additional)s, "environment": "%(environment)s", "logger": "%(name)s", "logging.googleapis.com/trace": "projects/{YOUR_PROJECT}/traces/%(otelTraceID)s", "logging.googleapis.com/spanId": "%(otelSpanID)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  main:
    class: logging.StreamHandler
    level: INFO
    formatter: mainFormatter
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: []

loggers:
  notify_api:
    level: INFO
    handlers: [main]
    propagate: no
  werkzeug:
    level: WARNING
    handlers: [main]
    propagate: no
  apiLogger:
    level: INFO
    handlers: [main]
    propagate: no
