steps:
- name: 'northamerica-northeast1-docker.pkg.dev/c4hnrd-tools/cicd-repo/gcp-sre'
  dir: "devops"
  secretEnv: ['OP_CONNECT_HOST', 'OP_CONNECT_TOKEN']
  script: |
    #!/usr/bin/env bash
    envs=(${_APP_DEPLOY_ENVIRONMENTS})
    for env_name in "${envs[@]}"; do
      export APP_ENV=${env_name}
      op inject  -f -i vaults.env -o vaults.${env_name}
      export VAL=$(awk -F= '{printf "- name: %s\n  value: %s\n", $1,$2}' vaults.${env_name} | sed 's/\"/\"/g')
      yq e '.spec.template.spec.containers[0].env += env(VAL)' ./gcp/k8s/service.template.yaml > ./gcp/k8s/service.${env_name}.yaml
    done

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${_DEPLOY_RUNNING_PROJECT_ID}/cloud-run-repo/notify-api:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag',
    '${_REGION}-docker.pkg.dev/${_DEPLOY_RUNNING_PROJECT_ID}/cloud-run-repo/notify-api:$SHORT_SHA',
    '${_REGION}-docker.pkg.dev/${_DEPLOY_RUNNING_PROJECT_ID}/cloud-run-repo/notify-api:${_APP_DEPLOY_ENVIRONMENT}']

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  dir: "devops/gcp"
  args:
      [
        'deploy', 'releases', 'create', 'v-$SHORT_SHA-${_RELEASE_TIMESTAMP}',
        '--to-target', '${_APP_DEPLOY_ENVIRONMENT}',
        '--delivery-pipeline', '${_DEPLOY_PIPELINE}',
        '--region', '${_REGION}',
        '--images', 'image-placeholder=${_REGION}-docker.pkg.dev/${_DEPLOY_RUNNING_PROJECT_ID}/cloud-run-repo/notify-api:$SHORT_SHA'
      ]
  entrypoint: gcloud

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  args:
      [
        'run', 'jobs', 'execute', 'notify-api-db-migration-${_APP_DEPLOY_ENVIRONMENT}',
        '--project', '${_APP_DEPLOY_PROJECT_ID}',
        '--region', '${_REGION}'
      ]
  entrypoint: gcloud

images:
- '${_REGION}-docker.pkg.dev/${_DEPLOY_RUNNING_PROJECT_ID}/cloud-run-repo/notify-api:$SHORT_SHA'
- '${_REGION}-docker.pkg.dev/${_DEPLOY_RUNNING_PROJECT_ID}/cloud-run-repo/notify-api:${_APP_DEPLOY_ENVIRONMENT}'

availableSecrets:
  secretManager:
  - versionName: projects/331250273634/secrets/OP_CONNECT_HOST/versions/latest
    env: 'OP_CONNECT_HOST'
  - versionName: projects/331250273634/secrets/OP_CONNECT_TOKEN/versions/latest
    env: 'OP_CONNECT_TOKEN'

options:
  automapSubstitutions: true
  substitutionOption: 'ALLOW_LOOSE'
substitutions:
  _APP_DEPLOY_ENVIRONMENTS: dev test sandbox prod
  _APP_DEPLOY_ENVIRONMENT: dev
  _APP_DEPLOY_PROJECT_ID: c4hnrd-dev
  _DEPLOY_RUNNING_PROJECT_ID: c4hnrd-tools
  _DEPLOY_PIPELINE: notify-api-pipeline
  _REGION: northamerica-northeast1

timeout: 3600s