apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: notify-api-config
profiles:
- name: dev
  manifests:
    rawYaml:
    - k8s/service.dev.yaml
- name: test
  manifests:
    rawYaml:
    - k8s/service.test.yaml
- name: sandbox
  manifests:
    rawYaml:
    - k8s/service.sandbox.yaml
- name: prod
  manifests:
    rawYaml:
    - k8s/service.test.yaml
deploy:
  cloudrun:
    projectid: deploy-project-id
#verify:
#- name: verify-integration-test
#  container:
#    name: integration-test
#    image: image-placeholder
#    command: ["./test_systems.sh"]
#customActions:
#- name: predeploy-action
#  containers:
#  - name: predeploy-echo
#    image: ubuntu
#    command: ["/bin/sh"]
#    args: ["-c", 'echo "this is a predeploy action"' ]
#- name: postdeploy-action
#  containers:
#  - name: postdeploy-echo
#    image: ubuntu
#    command: ["/bin/sh"]
#    args: ["-c", 'echo "this is a postdeploy action"' ]
