name: 'Copy firebase build deployment files'
description: ''

inputs:
  working_directory:
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    # Copy files
    - name: Copy build/deployment files
      shell: bash
      run: |
        cp  ${{ github.action_path }}/files/* {{ inputs.working_directory }}
