name: Backend Application CI Coverage

on:
  workflow_call:


jobs:
  code-coverage:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
      contents: write
      actions: read

    steps:
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          COMMENT_ARTIFACT_NAME: coveragefile
          COMMENT_FILENAME: coverage