name: OAS Spectral Linter CI

on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        default: "."
      oas_file_directory:
        type: string
        default: "./docs"

jobs:
  spectralChecks:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Copy spectral rule file (.spectral.yaml)
        uses: bcgov/bcregistry-sre/.github/actions/spectral-rule@main
        with:
          working-directory: ${{ inputs.working_directory }}

      - name: Setup Node
        uses: actions/setup-node@v4
        
      - name: Install spectral
        run: npm install --location=global @stoplight/spectral-cli
        
      - name: Spectral linting
        run: spectral lint ${{ inputs.oas_file_directory }}/*.yaml --ruleset .spectral.yaml --verbose

