name: Restart Services 10 minutes

on:
  schedule:
    # At every 10 minutes
    - cron: "10 * * * *"
  workflow_dispatch:
    inputs:
      environement:
        description: "Environment (dev/test/prod)"
        required: true
        default: "prod"

jobs:
  restart-services-10:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set env by input
        run: |
          echo "TAG_NAME=${{ github.event.inputs.environement }}" >> $GITHUB_ENV
      - name: Set env
        if: env.TAG_NAME == ''
        run: |
          echo "TAG_NAME=prod" >> $GITHUB_ENV
      - name: Login Openshift
        run: |
          oc login --server=${{secrets.OPENSHIFT4_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT4_SA_TOKEN}}


      - name: Restart entity-pay
        run: |
          oc scale --replicas=0 dc/entity-pay-${{ env.TAG_NAME }} -n cc892f-${{ env.TAG_NAME }}
          oc scale --replicas=1 dc/entity-pay-${{ env.TAG_NAME }} -n cc892f-${{ env.TAG_NAME }}


