name: 'Terraform-GCS'

on:
  workflow_dispatch:
    inputs:
      terraform_directory:
        description: 'Path to Terraform directory (e.g., gcp/terraform)'
        required: true
        type: string
        default: 'gcp/terraform'
      state_prefix:
        description: 'Prefix for Terraform state (e.g., iam)'
        required: true
        type: string
        default: 'iam'

env:
  TF_VAR_TFC_GCP_PROVIDER_AUTH: ${{ secrets.TFC_GCP_PROVIDER_AUTH }}
  TF_VAR_TFC_GCP_RUN_SERVICE_ACCOUNT_EMAIL: ${{ secrets.TFC_GCP_RUN_SERVICE_ACCOUNT_EMAIL }}
  TF_VAR_TFC_GCP_WORKLOAD_PROVIDER_NAME: ${{ secrets.TFC_GCP_WORKLOAD_PROVIDER_NAME }}

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        create_credentials_file: true
        export_environment_variables: true
        access_token_lifetime: 3600s
        access_token_scopes: |
          https://www.googleapis.com/auth/cloud-platform
          https://www.googleapis.com/auth/compute

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.5
        terraform_wrapper: false

    - name: Clear Terraform cache
      run: |
        rm -rf ~/.terraform.d/
        rm -rf ~/.terraformrc
        rm -rf .terraform/
        rm -f .terraform.lock.hcl
      working-directory: ${{ inputs.terraform_directory }}

    - name: Terraform Init
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        terraform init \
          -backend-config="bucket=common-tools-terraform-state" \
          -backend-config="prefix=${{ inputs.state_prefix }}" \
          -reconfigure \
          -input=false

    - name: Terraform Plan
      working-directory: ${{ inputs.terraform_directory }}
      run: terraform plan -input=false

    - name: Terraform Apply
      working-directory: ${{ inputs.terraform_directory }}
      run: terraform apply -auto-approve -input=false
